import type { CalculatorButtonConfig } from './types';

export const calculatorButtons: readonly CalculatorButtonConfig[] = Object.freeze([
  {
    id: 'clear',
    label: 'C',
    ariaLabel: 'Clear calculator',
    kind: 'clear',
  },
  {
    id: 'divide',
    label: '÷',
    ariaLabel: 'Divide',
    kind: 'operator',
    operator: 'divide',
  },
  {
    id: 'multiply',
    label: '×',
    ariaLabel: 'Multiply',
    kind: 'operator',
    operator: 'multiply',
  },
  {
    id: 'subtract',
    label: '−',
    ariaLabel: 'Subtract',
    kind: 'operator',
    operator: 'subtract',
  },
  {
    id: 'seven',
    label: '7',
    ariaLabel: 'Seven',
    kind: 'digit',
    digit: '7',
  },
  {
    id: 'eight',
    label: '8',
    ariaLabel: 'Eight',
    kind: 'digit',
    digit: '8',
  },
  {
    id: 'nine',
    label: '9',
    ariaLabel: 'Nine',
    kind: 'digit',
    digit: '9',
  },
  {
    id: 'add',
    label: '+',
    ariaLabel: 'Add',
    kind: 'operator',
    operator: 'add',
  },
  {
    id: 'four',
    label: '4',
    ariaLabel: 'Four',
    kind: 'digit',
    digit: '4',
  },
  {
    id: 'five',
    label: '5',
    ariaLabel: 'Five',
    kind: 'digit',
    digit: '5',
  },
  {
    id: 'six',
    label: '6',
    ariaLabel: 'Six',
    kind: 'digit',
    digit: '6',
  },
  {
    id: 'equals',
    label: '=',
    ariaLabel: 'Equals',
    kind: 'equals',
  },
  {
    id: 'one',
    label: '1',
    ariaLabel: 'One',
    kind: 'digit',
    digit: '1',
  },
  {
    id: 'two',
    label: '2',
    ariaLabel: 'Two',
    kind: 'digit',
    digit: '2',
  },
  {
    id: 'three',
    label: '3',
    ariaLabel: 'Three',
    kind: 'digit',
    digit: '3',
  },
  {
    id: 'zero',
    label: '0',
    ariaLabel: 'Zero',
    kind: 'digit',
    digit: '0',
  },
  {
    id: 'decimal',
    label: '.',
    ariaLabel: 'Decimal point',
    kind: 'decimal',
  },
]);
